function t199_showMenu(recid){var el=$('#rec'+recid);el.find('.t199__js__menu').each(function(){var $toggler=el.find('.t199__js__menu-toggler'),$menu=$(this),$body=$('body'),CLASS_MENU='t199__is__menu';$menu.find('.t199__menu-item').each(function(){var curUrl=$(this).attr('href');if(typeof curUrl!='undefined'&&curUrl.indexOf('#')>-1&&curUrl.substring(0,9)!='#submenu:'){$(this).on('click',function(e){$body.removeClass(CLASS_MENU)})}});$menu.find('.t199__menu-item-wrap .t-menusub__link-item').each(function(){var curUrl=$(this).attr('href');$(this).on('click',function(e){$body.removeClass(CLASS_MENU)})});$toggler.on('click',function(e){e.stopPropagation();e.preventDefault();$body.toggleClass(CLASS_MENU)});$(document).on('click',function(e){var clickedInsideMenu=$(e.target).hasClass('t199__js__menu')||$(e.target).parents('.t199__js__menu').length>0;if(!clickedInsideMenu){$body.removeClass(CLASS_MENU)}})});$('.t199__mmenu').bind('clickedAnchorInTooltipMenu',function(){$('body').removeClass('t199__is__menu')})}
function t199_positionHeader(recid){var el=$('#rec'+recid);var $header=el.find('.t199__js__header');var bgcolor=$header.css('background-color');var isScrolling=!1;var CLASS_ACTIVE='t199__is__active';function updateHeader(){isScrolling=!0;if($(window).scrollTop()>0){$header.addClass(CLASS_ACTIVE);$header.css('background-color','')}else{$header.removeClass(CLASS_ACTIVE);$header.css('background-color',bgcolor)}}
setInterval(function(){if(isScrolling){isScrolling=!1}},100);$(window).on('scroll',updateHeader);updateHeader()}
function t199_setPath(pageid){}
function t199_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=='/'){pathname=pathname.slice(1)}
if(pathname==''){pathname='/'}
$(".t199__menu a[href='"+url+"']").addClass('t-active');$(".t199__menu a[href='"+url+"/']").addClass('t-active');$(".t199__menu a[href='"+pathname+"']").addClass('t-active');$(".t199__menu a[href='/"+pathname+"']").addClass('t-active');$(".t199__menu a[href='"+pathname+"/']").addClass('t-active');$(".t199__menu a[href='/"+pathname+"/']").addClass('t-active')}
function t199_checkAnchorLinks(recid){if($(window).width()>=960){var t199_navLinks=$('#rec'+recid+" .t-menu__link-item:not(.tooltipstered)[href*='#']");if(t199_navLinks.length>0){t199_catchScroll(t199_navLinks)}}}
function t199_catchScroll(t199_navLinks){var t199_clickedSectionId=null,t199_sections=new Array(),t199_sectionIdTonavigationLink=[],t199_interval=100,t199_lastCall,t199_timeoutId;t199_navLinks=$(t199_navLinks.get().reverse());t199_navLinks.each(function(){var t199_cursection=t199_getSectionByHref($(this));if(typeof t199_cursection.attr('id')!='undefined'){t199_sections.push(t199_cursection)}
t199_sectionIdTonavigationLink[t199_cursection.attr('id')]=$(this)});t199_updateSectionsOffsets(t199_sections);$(window).bind('resize',t_throttle(function(){t199_updateSectionsOffsets(t199_sections)},200));$('.t199').bind('displayChanged',function(){t199_updateSectionsOffsets(t199_sections)});setInterval(function(){t199_updateSectionsOffsets(t199_sections)},5000);t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId);t199_navLinks.click(function(){if(!$(this).hasClass('tooltipstered')){t199_navLinks.removeClass('t-active');t199_sectionIdTonavigationLink[t199_getSectionByHref($(this)).attr('id')].addClass('t-active');t199_clickedSectionId=t199_getSectionByHref($(this)).attr('id')}});$(window).scroll(function(){var t199_now=new Date().getTime();if(t199_lastCall&&t199_now<t199_lastCall+t199_interval){clearTimeout(t199_timeoutId);t199_timeoutId=setTimeout(function(){t199_lastCall=t199_now;t199_clickedSectionId=t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId)},t199_interval-(t199_now-t199_lastCall))}else{t199_lastCall=t199_now;t199_clickedSectionId=t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId)}})}
function t199_updateSectionsOffsets(sections){$(sections).each(function(){var t199_curSection=$(this);t199_curSection.attr('data-offset-top',t199_curSection.offset().top)})}
function t199_getSectionByHref(curlink){var t199_curLinkValue=curlink.attr('href').replace(/\s+/g,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t199_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t199_curLinkValue.substring(1)+"']")}}
function t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId){var t199_scrollPosition=$(window).scrollTop(),t199_valueToReturn=t199_clickedSectionId;if(t199_sections.length!=0&&t199_clickedSectionId==null&&t199_sections[t199_sections.length-1].attr('data-offset-top')>t199_scrollPosition+300){t199_navLinks.removeClass('t-active');return null}
$(t199_sections).each(function(e){var t199_curSection=$(this),t199_sectionTop=t199_curSection.attr('data-offset-top'),t199_id=t199_curSection.attr('id'),t199_navLink=t199_sectionIdTonavigationLink[t199_id];if(t199_scrollPosition+300>=t199_sectionTop||(t199_sections[0].attr('id')==t199_id&&t199_scrollPosition>=$(document).height()-$(window).height())){if(t199_clickedSectionId==null&&!t199_navLink.hasClass('t-active')){t199_navLinks.removeClass('t-active');t199_navLink.addClass('t-active');t199_valueToReturn=null}else{if(t199_clickedSectionId!=null&&t199_id==t199_clickedSectionId){t199_valueToReturn=null}}
return!1}});return t199_valueToReturn}
function t410_init(recid){var el=$('#rec'+recid);var firstimgurl=el.find(".t410__wrapper").attr("data-juxtapose-imgurl-first");var firstimgdescr=el.find(".t410__wrapper").attr("data-juxtapose-imgdescr-first");var firstimgalt=el.find(".t410__wrapper").attr("data-juxtapose-imgalt-first");var secondimgurl=el.find(".t410__wrapper").attr("data-juxtapose-imgurl-second");var secondimgdescr=el.find(".t410__wrapper").attr("data-juxtapose-imgdescr-second");var secondimgalt=el.find(".t410__wrapper").attr("data-juxtapose-imgalt-second");t410_onObjLoad('juxtapose',function(){new juxtapose.JXSlider('#t410-juxtapose__'+recid,[{src:firstimgurl,label:firstimgdescr},{src:secondimgurl,label:secondimgdescr}],{animate:!1,showLabels:!0,showCredits:!1,startingPosition:'50%',makeResponsive:!0,callback:function(){if(firstimgalt.length>0){el.find('.t410__wrapper .jx-image.jx-left img').attr('alt',firstimgalt)}
if(secondimgalt.length>0){el.find('.t410__wrapper .jx-image.jx-right img').attr('alt',secondimgalt)}
if(window.isMobile){el.find('.t410__wrapper').append('<div class="t410__mobile_left"></div><div class="t410__mobile_right"></div>');var hanlerWidth=el.find('.jx-handle').width(),leftSide=el.find('.jx-image.jx-left'),rightSide=el.find('.jx-image.jx-right'),leftWidth=leftSide.width()-hanlerWidth/2,rightWidth=rightSide.width()-hanlerWidth/2,wrapper=el.find('.t410__wrapper'),mobileLeft=el.find('.t410__mobile_left'),mobileRight=el.find('.t410__mobile_right');mobileLeft.css('width',leftWidth);mobileRight.css('width',rightWidth);wrapper.on('touchend',function(){leftWidth=leftSide.width()-hanlerWidth/2;rightWidth=rightSide.width()-hanlerWidth/2;mobileLeft.css('width',leftWidth);mobileRight.css('width',rightWidth)})}}})});el.find('.t410').bind('displayChanged',function(){window.juxtapose.sliders.forEach(function(obj){if(obj.selector==='#t410-juxtapose__'+recid){console.log(obj);obj.setWrapperDimensions();return}})})}
function t410_onObjLoad(objName,okFunc,time){if(typeof window[objName]==='object'){okFunc()}else{var timerId=setTimeout(function checkFuncExist(){if(typeof window[objName]==='object'){okFunc();return}
timerId=setTimeout(checkFuncExist,time||100)})}}
function t509_setHeight(recid){var t509__el=$("#rec"+recid);var t509__image=t509__el.find(".t509__blockimg");t509__image.each(function(){var t509__width=$(this).attr("data-image-width");var t509__height=$(this).attr("data-image-height");var t509__ratio=t509__height/t509__width;var t509__padding=t509__ratio*100;$(this).css("padding-bottom",t509__padding+"%")});if($(window).width()>960){var t509__textwr=t509__el.find(".t509__textwrapper");var t509__deskimg=t509__el.find(".t509__desktopimg");t509__textwr.each(function(){$(this).css("height",t509__deskimg.innerHeight())})}}
function t604_init(recid){var el=$('#rec'+recid);t604_imageHeight(recid);t604_arrowWidth(recid);t604_show(recid);t604_hide(recid);$(window).bind('resize',t_throttle(function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)}));el.find('.t604').bind('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)})}
function t604_show(recid){var el=$("#rec"+recid),play=el.find('.t604__play');play.click(function(){if($(this).attr('data-slider-video-type')=='youtube'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t604__iframe\" width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
if($(this).attr('data-slider-video-type')=='vimeo'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t604__iframe\" width=\"100%\" height=\"100%\" src=\"https://player.vimeo.com/video/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
$(this).next().css('z-index','3')})}
function t604_hide(recid){var el=$("#rec"+recid),body=el.find('.t604__frame');el.on('updateSlider',function(){body.html('').css('z-index','')})}
function t604_imageHeight(recid){var el=$("#rec"+recid);var image=el.find(".t604__separator");image.each(function(){var width=$(this).attr("data-slider-image-width");var height=$(this).attr("data-slider-image-height");var ratio=height/width;var padding=ratio*100;$(this).css("padding-bottom",padding+"%")})}
function t604_arrowWidth(recid){var el=$("#rec"+recid),arrow=el.find('.t-slds__arrow_wrapper'),slideWidth=el.find('.t-slds__wrapper').width(),windowWidth=$(window).width(),arrowWidth=windowWidth-slideWidth;if(windowWidth>960){arrow.css('width',arrowWidth/2)}else{arrow.css('width','')}}
function t650_unifyHeights(recid){if($(window).width()>=960){$('#rec'+recid+' .t650 .t-container .t650__row').each(function(){var t650_highestBox=0,t650_currow=$(this);$('.t650__inner-col',this).each(function(){var t650_curCol=$(this),t650_curText=t650_curCol.find(".t650__text"),t650_curBtn=t650_curCol.find(".t650__btn-container"),t650_curColHeight=t650_curText.outerHeight()+t650_curBtn.outerHeight();if(t650_curColHeight>t650_highestBox){t650_highestBox=t650_curColHeight}});$('.t650__inner-col',this).css('height',t650_highestBox)})}else{$('.t650__inner-col').css('height','auto')}}